# Generated by Django 2.1.8 on 2019-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='이미지텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('파일', models.ImageField(upload_to='')),
                ('설명', models.CharField(blank=True, max_length=255)),
                ('시간', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '이미지',
                'verbose_name_plural': '이미지들',
            },
        ),
    ]
