# Generated by Django 2.1.8 on 2019-05-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='게시판테이블헤드',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('헤더', models.CharField(max_length=10)),
            ],
        ),
    ]
