# Generated by Django 2.1.8 on 2019-05-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_게시판테이블헤드_순서'),
    ]

    operations = [
        migrations.RenameField(
            model_name='게시판텝',
            old_name='게시판설명',
            new_name='설명',
        ),
        migrations.RenameField(
            model_name='게시판텝',
            old_name='게시판명',
            new_name='이름',
        ),
    ]
