# Generated by Django 2.1.8 on 2019-05-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190524_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='게시물텝',
            name='변경자',
        ),
        migrations.RemoveField(
            model_name='게시물텝',
            name='생성자',
        ),
        migrations.RemoveField(
            model_name='게시물텝',
            name='주제',
        ),
        migrations.RemoveField(
            model_name='주제텝',
            name='게시판',
        ),
        migrations.RemoveField(
            model_name='주제텝',
            name='주최자',
        ),
        migrations.DeleteModel(
            name='게시물텝',
        ),
        migrations.DeleteModel(
            name='게시판텝',
        ),
        migrations.DeleteModel(
            name='주제텝',
        ),
    ]
