# Generated by Django 2.1.8 on 2019-05-23 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0005_auto_20190524_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='게시물텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('글', models.TextField(max_length=4000)),
                ('생성일', models.DateTimeField(auto_now_add=True)),
                ('변경일', models.DateTimeField(null=True)),
                ('변경자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('생성자', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='게시물들', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='게시판텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('이름', models.CharField(max_length=30)),
                ('설명', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='주제텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('주제', models.CharField(max_length=255)),
                ('발행일', models.DateTimeField(auto_now_add=True)),
                ('게시판', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='주제들', to='boards.게시판텝')),
                ('주최자', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='주제들', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='게시물텝',
            name='주제',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='게시물들', to='boards.주제텝'),
        ),
    ]
