# Generated by Django 2.1.8 on 2019-05-24 04:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0006_auto_20190524_0630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='게시물텝',
            new_name='글텝',
        ),
    ]
