# Generated by Django 2.1.8 on 2019-05-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20190524_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='게시판테이블헤드',
            new_name='게시판테이블헤드텝',
        ),
    ]
