# Generated by Django 2.1.8 on 2019-05-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20190524_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='주제텝',
            old_name='주최자',
            new_name='게시자',
        ),
    ]
