# Generated by Django 2.1.8 on 2019-05-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_주제그리드헤드텝'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='게시판테이블헤드텝',
            new_name='게시판그리드헤드텝',
        ),
    ]
