# Generated by Django 2.1.8 on 2019-05-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_auto_20190524_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='글텝',
            old_name='변경일',
            new_name='수정일',
        ),
        migrations.RenameField(
            model_name='글텝',
            old_name='변경자',
            new_name='수정자',
        ),
        migrations.RenameField(
            model_name='글텝',
            old_name='생성일',
            new_name='작성일',
        ),
        migrations.RenameField(
            model_name='글텝',
            old_name='생성자',
            new_name='작성자',
        ),
    ]
