# Generated by Django 2.1.8 on 2019-05-25 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20190525_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='글텝',
            name='작성자',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='글들', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='글텝',
            name='주제',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='글들', to='boards.주제텝'),
        ),
    ]
