# Generated by Django 2.1.8 on 2019-05-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_auto_20190525_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='주제텝',
            old_name='발행일',
            new_name='게시일',
        ),
    ]
