# Generated by Django 2.1.8 on 2019-05-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_auto_20190525_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='주제텝',
            name='조회수',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
