# Generated by Django 2.1.8 on 2019-05-25 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_주제텝_조회수'),
    ]

    operations = [
        migrations.RenameField(
            model_name='글텝',
            old_name='댓글일',
            new_name='수정일',
        ),
        migrations.RenameField(
            model_name='글텝',
            old_name='댓글자',
            new_name='수정자',
        ),
    ]
