# Generated by Django 2.1.8 on 2019-05-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_auto_20190526_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='그리드헤드텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('순서', models.IntegerField(null=True)),
                ('헤더', models.CharField(max_length=30)),
                ('텝명', models.CharField(max_length=30)),
            ],
        ),
    ]
