# Generated by Django 2.1.8 on 2019-05-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_그리드헤드텝'),
    ]

    operations = [
        migrations.RenameField(
            model_name='그리드헤드텝',
            old_name='텝명',
            new_name='그리드',
        ),
    ]
