# Generated by Django 2.1.8 on 2019-06-03 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='성경책텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('책명', models.IntegerField(max_length=20)),
                ('언어', models.IntegerField(max_length=10)),
                ('작성일', models.DateTimeField(auto_now_add=True)),
                ('수정일', models.DateTimeField(null=True)),
                ('작성자', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='작성자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
