# Generated by Django 2.1.8 on 2019-06-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_auto_20190604_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='성경권텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('권명', models.CharField(max_length=20)),
                ('구분', models.CharField(max_length=20)),
                ('순서', models.IntegerField()),
                ('절수', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='성경장텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('번호', models.IntegerField()),
                ('권명', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='장들', to='bible.성경권텝')),
            ],
        ),
        migrations.CreateModel(
            name='성경절텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('번호', models.IntegerField()),
                ('징', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='장들', to='bible.성경장텝')),
            ],
        ),
        migrations.AlterField(
            model_name='성경책텝',
            name='언어',
            field=models.IntegerField(choices=[(1, '한국어'), (2, 'English')]),
        ),
        migrations.AddField(
            model_name='성경권텝',
            name='서명',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='권들', to='bible.성경책텝'),
        ),
    ]
