# Generated by Django 2.1.8 on 2019-06-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0008_성경절텝'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='성경절텝',
            name='id',
        ),
        migrations.AlterField(
            model_name='성경절텝',
            name='번호',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
