# Generated by Django 2.1.8 on 2019-06-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0010_auto_20190604_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='성경절텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('번호', models.PositiveIntegerField()),
                ('내용', models.TextField()),
                ('문단시작', models.BooleanField(default=False)),
                ('징', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='장들', to='bible.성경장텝')),
            ],
        ),
    ]
