# Generated by Django 2.1.8 on 2019-06-03 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0011_성경절텝'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='성경절텝',
            name='징',
        ),
        migrations.AddField(
            model_name='성경절텝',
            name='장번호',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='절들', to='bible.성경장텝'),
        ),
    ]
