# Generated by Django 2.1.8 on 2019-06-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0012_auto_20190604_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='성경문단텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(max_length=100)),
                ('권명', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='문단들', to='bible.성경권텝')),
            ],
        ),
    ]
