# Generated by Django 2.1.8 on 2019-06-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0013_성경문단텝'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='성경권텝',
            name='서명',
        ),
        migrations.RemoveField(
            model_name='성경문단텝',
            name='권명',
        ),
        migrations.RemoveField(
            model_name='성경장텝',
            name='권명',
        ),
        migrations.RemoveField(
            model_name='성경절텝',
            name='장번호',
        ),
        migrations.RemoveField(
            model_name='성경책텝',
            name='작성자',
        ),
        migrations.DeleteModel(
            name='성경권텝',
        ),
        migrations.DeleteModel(
            name='성경문단텝',
        ),
        migrations.DeleteModel(
            name='성경장텝',
        ),
        migrations.DeleteModel(
            name='성경절텝',
        ),
        migrations.DeleteModel(
            name='성경책텝',
        ),
    ]
