# Generated by Django 2.1.8 on 2019-06-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0015_auto_20190604_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='성경글텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(max_length=100)),
                ('권', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='글들', to='bible.성경권텝')),
            ],
        ),
        migrations.RemoveField(
            model_name='성경문단텝',
            name='권명',
        ),
        migrations.RenameField(
            model_name='성경장텝',
            old_name='권명',
            new_name='권',
        ),
        migrations.RenameField(
            model_name='성경절텝',
            old_name='장번호',
            new_name='장',
        ),
        migrations.DeleteModel(
            name='성경문단텝',
        ),
        migrations.AddField(
            model_name='성경절텝',
            name='글',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='절들', to='bible.성경글텝'),
        ),
    ]
