# Generated by Django 2.1.8 on 2019-06-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0016_auto_20190604_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='성경글텝',
            name='권',
        ),
        migrations.RemoveField(
            model_name='성경절텝',
            name='글',
        ),
        migrations.DeleteModel(
            name='성경글텝',
        ),
    ]
