# Generated by Django 2.1.8 on 2019-06-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0017_auto_20190604_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='성경글텝',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(max_length=100)),
                ('시작장', models.PositiveIntegerField()),
                ('시작절', models.PositiveIntegerField()),
                ('종료장', models.PositiveIntegerField()),
                ('종료절', models.PositiveIntegerField()),
                ('권', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='글들', to='bible.성경권텝')),
            ],
        ),
    ]
